# https://docs.gradle.org/current/userguide/performance.html
org.gradle.parallel=true
org.gradle.daemon=true
org.gradle.caching=false
# let Gradle discover the JDKs installed by actions/setup-java as toolchains
org.gradle.java.installations.fromEnv=JAVA_HOME_8_X64,JAVA_HOME_11_X64,JAVA_HOME_17_X64,JAVA_HOME_21_X64,JAVA_HOME_25_X64
lombok.version=1.18.46
sevenzipjbinding.version=16.02-2.01
org.gradle.configuration-cache=true
